@startuml
top to bottom direction

package "Мотивация - это то что заставляет нас меняться" as motive #f5e0e6 {  
  rectangle "Контекст - это то что нас ограничивает и способствует к изменениям" as context #d0e4f4 {
    object "Стимулы \n- это текущее состояние (as-is)" as incentives #ffffff {
      1. Это то что заставляет\n двигаться стейкхолдеров
    }

    object "Фактический ландшафт" as landscape #ffffff {
      1. Текущее устройство контекста
      2. Существующие процессы
    }

    object "Зависимости" as dependencies #ffffff {
      1. Политические/экономические
      2. Требования регуляторов
      3. Культурные особенности
    }

    object "Доступные ресурсы" as resources #ffffff {
      1. Что мы готовы потратить чтобы достичь цели
      2. Когда мы должны достичь цели
    }

    object "Закономерности существующего контекста" as patterns #ffffff {
      1. Почему контекст такой какой он сейчас есть
      2. Традиции и культура принятия решений
      3. Традиции и культура реализации решений
      4. Особенности оценки текущего контекста
    }
  }

  rectangle "Ожидаемый результат" as result #b3d9f2 {
    object "Потребности" as needs #ffffff {
      1. К чему я мотивирован
    }
    object "Критерии оценки успешности" as success_criteria #ffffff {
      1. Когда будет сделано?
      2. Сколько будет потрачено?
      3. Сколько будет заработано или съэкономлено
      4. Какие риски/возможности возникают\n и какие будут минимизированы или устранены
    }

    object "Предубеждения о верном решении" as prejudices #ffffff {
      1. Мнение стейкхолдеров о том\n как должно быть правильно
      2. Личный опыт и практика
      3. Индустриальные стандарты\n и внешняя практика
    }

    object "Требования" as requirements #ffffff {
      1. Что приемлемо или что неприемлемо
      2. Функциональные и нефункциональные
    }

    object "Кто будет делать" as responsible #ffffff {
      1. Своими ресурсами
      2. Ресурсами подрядчика/вендора
      3. Уникальность/массовость решения
    }
  }

  rectangle "Архитектурное решение" as solution #99c2e6 {
    object "Назначение ресурсов" as purpose #ffffff {
      1. Какие ресурсы для реализации\n архитектурного решения необходимы
    }
    object "План реализации" as plan #ffffff {
      1. Этапы реализации и их зависимости
      2. График реализации
      3. Распределение ресурсов по графику
    }
    object "Критерии приёмки" as acceptance_criteria #ffffff {
      1. Оценка реализации потребности
      2. Оценка реализации требований\n (функциональные и нефункциональные)
      3. Оценка использования ресурсов
      4. Оценка ожидаемых результатов
    }
    object "Обоснование архитектурного решения для стейкхолдеров" as justification #ffffff {
      1. Для ключевого стейкхолдера с отражением\n удовлетворения потребности
      2. Для стейкхолдеров с отражением\n удовлетворения требованиям
    }
    object "Инкремент изменения ландшафта" as increment #ffffff {
      1. Изменения в информационных системах
      2. Изменения в процессах
      3. Изменения в орг структуре
      4. Т.д.
    }
  }

  rectangle "Исполнение" as execution #80b3d9 {
    object "Контроль" as control #ffffff {
      1. Утилизации ресурсов для\n эффективной реализации арх. решения
    }
    object "Управление изменениями" as change_management #ffffff {
      1. Контроль состоятельности архитектурного\n решения в условиях состоявшихся изменений
      2. Поддержание рационального контекста\n в сознании стейкхолдеров
    }
    object "Управление знаниями и компетенциями" as knowledge_management #ffffff {
      1. Экспертное лидерство
      2. Координация передачи знаний\n необходимых для реализации арх решений
      3. Наставничество
      4. Личное экспертное развитие
    }
    object "Непосредственное участие в исполнении" as participation #ffffff {
      1. Гэмба
      2. Участие в создании производственных артефактов
      3. Участие в развитии производственных процессов
    }
    object "Управление инженерной культурой" as culture #ffffff {
      1. Культура принятия ключевых решений
      2. Культура объективности
      3. Лидерство
    }
  }
  
  rectangle "Рефлексия" as reflection #66a3cc {
    object "Анализ" as analysis #ffffff {
      1. Успехи и их причины
      2. Неудачи и их причины
    }
  }

  context -down-> result
  result -down-> solution
  solution -down-> execution
  execution -down-> reflection
}
@enduml