entities:
  seaf.ba.products:
    title: Продукты или услуги
    schema:
      type: object
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          type: object
          properties:
            title:
              title: Наименование
              type: string
            description:
              title: Описание
              type: string
            owner:
              title: Владелец продукта
              type: string
              $ref: "#/$rels/seaf.ba.paries.parties"
            used_in:
              title: используется в
              type: array
              items:
                $ref: "#/$rels/seaf.ba.products.product"
          required:
            - title
            - owner
    objects:
      product:
        route: "/"
        title: Продукт-услуга
        symbol: "prd"
